name: build-site

# Run this when there is a pull request on the main branch
on:
  pull_request:
    branches:
    - main

# This job installs dependencies and builds the book, to see if there are any errors
jobs:
  build-site:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v3

    # Install dependencies
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Build the book
    - name: Build the book
      run: |
        jupyter-book build .
